#!/usr/bin/env sh
# claude-dedrift self-healing shim.
# Keeps the Claude Code binary patched across auto-updates, then hands off to it.
# Generated by `claude-dedrift install` — edit via the tool, not by hand.

CLAUDE_LINK="@@CLAUDE_LINK@@"
STATE_DIR="@@STATE_DIR@@"

# Follow the symlink chain to the concrete versioned binary (POSIX, no readlink -f).
resolve() {
  p="$1"
  while [ -L "$p" ]; do
    t="$(readlink "$p")"
    case "$t" in
      /*) p="$t" ;;
      *)  p="$(dirname "$p")/$t" ;;
    esac
  done
  printf '%s\n' "$p"
}

REAL="$(resolve "$CLAUDE_LINK")"

# Never block the user from launching Claude Code, whatever happens below.
if [ -z "$REAL" ] || [ ! -x "$REAL" ]; then
  printf 'claude-dedrift: cannot find the real claude binary via %s\n' "$CLAUDE_LINK" >&2
  exec "$CLAUDE_LINK" "$@"
fi

MARKER="$STATE_DIR/patched/$(basename "$REAL")"

if [ ! -f "$MARKER" ]; then
  if claude-dedrift apply --target "$REAL" --quiet; then
    mkdir -p "$STATE_DIR/patched" 2>/dev/null && : > "$MARKER"
  else
    printf 'claude-dedrift: could not patch %s — launching unpatched\n' "$REAL" >&2
  fi
fi

exec "$REAL" "$@"
